### PR TITLE
Updated for compliance with pep8

### PR DESCRIPTION
**Pull request by vedtopkar**

### CODE REVIEW

**Comment by vedtopkar** [comment]
@martinaryee let me know if you're cool with merging this!

**Comment by martinaryee** [comment]
Should we merge into dev instead or do you want to go straight to master?

**Comment by vedtopkar** [comment]
Oh shoot, you're right. 

Perhaps as a convention we should rerun the dev branch on the full dataset before we merge dev into master?

**Comment by martinaryee** [comment]
Running the full dataset test on dev before merging into master is a good idea. I had started to put together some automation for doing this but it needs some polishing:
https://github.com/aryeelab/guideseq/blob/master/test/large_test.sh
(It's not written as a proper test yet)

**Pull request closed without merging**
